FROM php:8.2-cli

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip git libgmp-dev \
    && docker-php-ext-install gmp \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY core ./core
COPY pay-server ./pay-server

WORKDIR /app/pay-server
RUN composer install --no-dev --optimize-autoloader --no-interaction

CMD ["php", "watcher/bin/watch.php"]
